services:
  mysql:
    image: mysql:8.0
    container_name: vacinacao_db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: vacinacao_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vacinacao_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vacinacao_app
    image: vacinacao_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: vacinacao_db
    networks:
      - vacinacao_network
    stdin_open: true
    tty: true

volumes:
  mysql_data:

networks:
  vacinacao_network:
    driver: bridge
