version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: agenda_db
    environment:
      POSTGRES_DB: agenda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - agenda_db_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/02-dump.sql
    networks:
      - agenda_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: agenda_app
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    networks:
      - agenda_network
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: agenda
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  agenda_db_data:

networks:
  agenda_network:
    driver: bridge
